---
- name: Install and configure node expoter
  hosts: all
  become: yes
  tasks:
        - name: Create node_exporter group
          group:
            name: node_exporter
            state: present
        - name: Create node_exporter user with /shell/false shell
          user:
            name: node_exporter
            shell: /bin/false
            groups: node_exporter
        - name: download node exporter
          get_url:
            url: https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-amd64.tar.gz
            dest: /root/
        - name: Unarchive node_exporter
          unarchive:
            src: /root/node_exporter-0.18.1.linux-amd64.tar.gz
            dest: /root/
            remote_src: yes
        - name: copy node_exporter to /usr/local/bin/
          shell: cp /root/node_exporter-0.18.1.linux-amd64/node_exporter  /usr/local/bin/
        - name:
          file:
            path: /usr/local/bin/node_exporter
            owner: node_exporter
            group: node_exporter
        - name: create node_exporter service
          shell: |
            echo '[Unit]
            Description=Node Exporter
            Wants=network-online.target
            After=network-online.target

            [Service]
            User=node_exporter
            Group=node_exporter
            Type=simple
            ExecStart=/usr/local/bin/node_exporter

            [Install]
            WantedBy=multi-user.target' >> /etc/systemd/system/node_exporter.service
        - name: reload the systemd daemon
          systemd: daemon_reload=yes
        - name: start and enable node_exporter
          systemd:
            name: node_exporter.service
            state: started
            enabled: True
        - name: check if node_exporter has port 9100 open
          shell: ss -tp state listening sport = :9100 | grep node_exporter
